name: Swift

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SwiftLint
        run: swiftlint --config .swiftlint.yml --reporter github-actions-logging --strict

