name: Swift

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/realm/swiftlint:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SwiftLint
        run: swiftlint --config .swiftlint.yml --reporter github-actions-logging --strict

  test:
    name: Test
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v3
    - name: Build and test
      run: xcodebuild -project ReadBeeb.xcodeproj -scheme ReadBeeb -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.0' test
